packages:
  - packages/*
  - packages/libs/shared/*
  - examples/*
  - docs/

autoInstallPeers: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - argon2
  - bcrypt
  - core-js
  - core-js-pure
  - esbuild
  - nx
  - protobufjs
  - sharp
  - unrs-resolver
