/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export enum PublicProviderType {
  LOCAL = "LOCAL",
  OIDC = "OIDC",
}

export enum PublicWorkspaceUserRole {
  MEMBER = "MEMBER",
  OWNER = "OWNER",
}

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface OidcProvider {
  consumed: Generated<boolean>;
  expiresAt: Timestamp | null;
  grantId: string | null;
  id: string;
  payload: Json;
  uid: string | null;
  userCode: string | null;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: Generated<boolean>;
  firstName: string;
  id: Generated<string>;
  lastName: string;
  name: string;
  passwordHash: string | null;
  pictureUrl: string | null;
  providerId: string;
  providerMetadata: Json | null;
  providerType: PublicProviderType;
  updatedAt: Generated<Timestamp>;
  username: string;
}

export interface Workspace {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  description: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
  updatedBy: string;
  workspaceId: Generated<string>;
}

export interface WorkspaceUser {
  addedAt: Generated<Timestamp>;
  addedBy: string;
  role: PublicWorkspaceUserRole;
  userId: string;
  workspaceId: string;
}

export interface DB {
  oidcProvider: OidcProvider;
  users: User;
  workspaces: Workspace;
  workspaceUsers: WorkspaceUser;
}
